# Description: Update ADSS Rules using GitHub Actions
#
# This is free software, licensed under the GPL v3 License.
# See /LICENSE for more information.

name: 镜像同步

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  push:

jobs:
  synchronization:
    name: 镜像同步
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
    
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set TimeZone
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"

      - name: Update Mirrors To Other Repos
        run: |
          rm -rf .git/
          git init         
          git config --global  user.name "clion007"
          git config --global  user.email "clion007@126.com"
          git remote add origin https://clion007:${{ secrets.GITCODE_TOKEN }}@gitcode.net/clion007/adss.git
          git add .
          git commit -am "Auto update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
          git push -f -u origin master
      
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 0
          keep_minimum_runs: 5
