# Description: Update ADSS Rules using GitHub Actions
#
# This is free software, licensed under the GPL v3 License.
# See /LICENSE for more information.

name: Update Rules

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *

jobs:
  Update:
    name: Update Rules
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
    
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set TimeZone
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
      
      - name: Build Rules
        run: |
          chmod 777 ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          . ./adss.sh && show_copyright
          ./rules/builder/build.sh
          mv -f /tmp/adss/dnsrules.conf ./rules/file/dnsrules.conf
          mv -f /tmp/adss/hostsrules.conf ./rules/file/hostsrules.conf

      - name: Git Auto Update Rules
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: Clion <clion007@126.com>
          file_pattern: rules/file/*rules.conf
      
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 0
          keep_minimum_runs: 5